//Random array of comments for seed data

const comments = [
    "❤️",
    "That's interesting!",
    "👍",
    "I agree with you.",
    "😄",
    "I can relate to this.",
    "😪",
    "Well said!",
    "😑",
    "Great post!",
    "🙁",
    "Thanks for sharing.",
    "😥",
    "You've got a point.",
    "👀",
    "I'm not sure about that.",
    "🌟",
    "This made me smile.",
    "👻",
    "I'm feeling inspired.",
    "😢",
    "I needed to hear this.",
    "🤯",
    "You're so right!",
    "😎",
    "This is helpful.",
    "😬",
    "I've had a similar experience.",
    "💪",
    "I disagree with you.",
    "🤗",
    "Tell me more about it.",
    "🎊",
    "I'm curious about this.",
    "😓",
    "Can you elaborate?",
    "👋",
    "I appreciate your perspective.",
    "😔",
    "This changed my mind.",
    "🥳",
    "I'm impressed!",
    "👑",
    "You're onto something here.",
    "😱",
    "I'm touched by your post.",
    "🚀",
    "I've never thought of that before.",
    "😇",
    "Interesting point of view.",
    "😃",
    "I'm with you on this.",
    "👀",
    "Thanks for the insights.",
    "😆",
    "I've been through this too.",
    "👊",
    "This made me think.",
    "😮",
    "You made my day.",
    "😴", ,
    "I can't stop thinking about your post.",
    "😋",
    "This is eye-opening.",
    "🤔",
    "You've opened my mind.",
    "👌",
    "I'm sharing this with my friends.",
    "🤭",
    "You've articulated it perfectly.",
    "🥰",
    "I've shared a similar experience.",
    "👀",
    "This is worth discussing.",
    "🙏",
    "I'm sending this to my family.",
    "💯",
    "You've got me thinking now.",
    "😂",
    "I'm going to remember this.",
    "🎉",
    "You've got a new follower.",
    "🙌",
    "This deserves more attention.",
    "🤩",
    "I'm in awe of your post.",
    "👏",
    "This is so relatable.",
    "😎",
    "I can't agree more.",
    "😊",
    "You've got my support.",
    "🔥",
    "This is so thought-provoking.",
    "😍",
    "I'm cheering for you.",
    "😁"
];

module.exports = comments;